export type VoiceProviderId = "google_gemini" | "google_chirp" | "sarvam" | "elevenlabs" | "murf" | "edge_neural" | "ai4bharat_indic";

export interface VoiceSpeaker {
  id: string;
  name: string;
  nativeName?: string;
  provider: VoiceProviderId;
  gender: "female" | "male";
  language: string;
  languageName: string;
  accent: string;
  model: string;
  description: string;
  category: "conversational" | "telephony" | "expressive" | "standard";
  recommendedForTelugu?: boolean;
  recommendedTag?: string;
  sampleText?: string;
  defaultRate?: number;
  defaultPitch?: number;
  supportedSampleRates: number[];
  avatarUrl?: string;
}

export interface VoiceProviderConfig {
  id: VoiceProviderId;
  name: string;
  badge: string;
  brandColor: string;
  description: string;
  tagline: string;
  models: { id: string; name: string; description: string; latencyClass: "ultra-low" | "low" | "standard" }[];
  supportedSampleRates: number[];
  supportsStreaming: boolean;
  supportsBargeIn: boolean;
  supportsPhoneMode8kHz: boolean;
  docsUrl: string;
  speakers: VoiceSpeaker[];
}

// 0. GOOGLE GEMINI VOICE - Flagship Ultra-Natural Zero-Cost Voice Models
export const GOOGLE_GEMINI_SPEAKERS: VoiceSpeaker[] = [
  // Females
  {
    id: "gemini-kore",
    name: "Kore (Gemini Flash Natural)",
    nativeName: "కోరే",
    provider: "google_gemini",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Google Gemini Neural Conversational",
    model: "gemini-3.1-flash-tts-preview",
    description: "Google Gemini flagship natural female voice. Ultra-smooth conversational flow, rich intonation, and pristine pronunciation of Telugu, English, and Tanglish words.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Official Google Gemini Telugu Pick",
    defaultRate: 1.08,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000, 48000],
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "gemini-aoede",
    name: "Aoede (Gemini Expressive)",
    nativeName: "అయోడి",
    provider: "google_gemini",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Google Gemini Expressive Counselor",
    model: "gemini-3.1-flash-tts-preview",
    description: "Highly expressive, empathetic admissions counselor voice. Perfect for detailed course explanations and student queries.",
    category: "expressive",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Recommended Female Counselor",
    defaultRate: 1.1,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000, 48000],
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "gemini-leda",
    name: "Leda (Gemini Reassuring)",
    nativeName: "లెడా",
    provider: "google_gemini",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Google Gemini Calm & Articulate",
    model: "gemini-3.1-flash-tts-preview",
    description: "Calm, polite, and reassuring receptionist cadence. Outstanding syllable articulation for pricing and schedule details.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Best for Admissions & Fees",
    defaultRate: 1.06,
    defaultPitch: 0.99,
    supportedSampleRates: [8000, 16000, 24000, 48000],
  },
  {
    id: "gemini-zephyr",
    name: "Zephyr (Gemini Dynamic)",
    nativeName: "జెఫిర్",
    provider: "google_gemini",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Google Gemini Modern Snappy",
    model: "gemini-3.1-flash-tts-preview",
    description: "Bright, energetic receptionist cadence with rapid turn-taking responsiveness for telephone callers.",
    category: "telephony",
    defaultRate: 1.15,
    defaultPitch: 1.04,
    supportedSampleRates: [8000, 16000, 24000, 48000],
  },
  {
    id: "gemini-callisto",
    name: "Callisto (Gemini Executive)",
    nativeName: "కాలిస్టో",
    provider: "google_gemini",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Google Gemini Professional",
    model: "gemini-3.1-flash-tts-preview",
    description: "Crisp, authoritative, executive female advisor tone suited for corporate programs and placement updates.",
    category: "standard",
    defaultRate: 1.08,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000, 48000],
  },

  // Males
  {
    id: "gemini-puck",
    name: "Puck (Gemini Flash Natural)",
    nativeName: "పక్",
    provider: "google_gemini",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Google Gemini Dynamic Male",
    model: "gemini-3.1-flash-tts-preview",
    description: "Google Gemini flagship natural male voice. Friendly, clear, and confident phone admissions advisor.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Official Google Gemini Male Pick",
    defaultRate: 1.1,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000, 48000],
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "gemini-charon",
    name: "Charon (Gemini Resonant)",
    nativeName: "కారాన్",
    provider: "google_gemini",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Google Gemini Deep Resonant",
    model: "gemini-3.1-flash-tts-preview",
    description: "Deep, trustworthy, and composed senior admissions counselor tone with high credibility.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Recommended Senior Advisor",
    defaultRate: 1.05,
    defaultPitch: 0.96,
    supportedSampleRates: [8000, 16000, 24000, 48000],
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "gemini-fenrir",
    name: "Fenrir (Gemini Tech Lead)",
    nativeName: "ఫెన్రిర్",
    provider: "google_gemini",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Google Gemini Articulate Male",
    model: "gemini-3.1-flash-tts-preview",
    description: "Sharp, articulate male instructor tone. Outstanding for explaining technical modules and real-time projects.",
    category: "telephony",
    defaultRate: 1.12,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000, 48000],
  },
  {
    id: "gemini-orus",
    name: "Orus (Gemini Friendly)",
    nativeName: "ఓరస్",
    provider: "google_gemini",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Google Gemini Warm Male",
    model: "gemini-3.1-flash-tts-preview",
    description: "Warm, supportive, student-friendly mentor cadence for friendly onboarding.",
    category: "conversational",
    defaultRate: 1.08,
    defaultPitch: 0.99,
    supportedSampleRates: [8000, 16000, 24000, 48000],
  },
];

// 1. SARVAM AI - Bulbul V3 Voice Catalog
export const SARVAM_SPEAKERS: VoiceSpeaker[] = [
  // Telugu Recommended Females
  {
    id: "neha",
    name: "Neha",
    nativeName: "నేహ",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native / Telangana & Andhra",
    model: "bulbul:v3",
    description: "Sarvam recommended primary Telugu female voice. Warm, natural conversational pacing and clear intonation.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Official Sarvam Telugu Pick",
    defaultRate: 1.1,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "priya",
    name: "Priya",
    nativeName: "ప్రియ",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native / Modern Urban",
    model: "bulbul:v3",
    description: "Sarvam recommended female voice. Articulate, professional, and friendly academic counseling tone.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Recommended Female",
    defaultRate: 1.12,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
  },
  // Other Bulbul V3 Females
  {
    id: "ritu",
    name: "Ritu",
    nativeName: "రీతు",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu & Indic Multilingual",
    model: "bulbul:v3",
    description: "Youthful and energetic reception voice for dynamic student engagement.",
    category: "conversational",
    defaultRate: 1.1,
    defaultPitch: 1.05,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "pooja",
    name: "Pooja",
    nativeName: "పూజ",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "South Indian Regional",
    model: "bulbul:v3",
    description: "Calm, polite, and reassuring receptionist cadence for query resolution.",
    category: "conversational",
    defaultRate: 1.05,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "simran",
    name: "Simran",
    nativeName: "సిమ్రన్",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu & Urban Code-Mixed",
    model: "bulbul:v3",
    description: "Crisp conversational tone with natural handling of English technical terms.",
    category: "conversational",
    defaultRate: 1.15,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "kavya",
    name: "Kavya",
    nativeName: "కావ్య",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native / Fast Conversational",
    model: "bulbul:v3",
    description: "Fast, confident, and responsive for quick turn-taking during phone inquiries.",
    category: "telephony",
    defaultRate: 1.2,
    defaultPitch: 1.04,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "ishita",
    name: "Ishita",
    nativeName: "ఇషిత",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu & English Fluent",
    model: "bulbul:v3",
    description: "Clear and polished tone, ideal for corporate admissions and course scheduling.",
    category: "conversational",
    defaultRate: 1.08,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "shreya",
    name: "Shreya",
    nativeName: "శ్రేయ",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Hyderabad Accent",
    model: "bulbul:v3",
    description: "Warm conversational Telugu with authentic regional cadence and inflection.",
    category: "conversational",
    defaultRate: 1.1,
    defaultPitch: 1.03,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "roopa",
    name: "Roopa",
    nativeName: "రూప",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native Andhra Accent",
    model: "bulbul:v3",
    description: "Gentle and patient delivery, great for detailed course curriculum explanations.",
    category: "conversational",
    defaultRate: 1.05,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "tanya",
    name: "Tanya",
    nativeName: "తాన్య",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Modern Code-Mixed",
    model: "bulbul:v3",
    description: "Contemporary conversational tone with snappy responses.",
    category: "conversational",
    defaultRate: 1.12,
    defaultPitch: 1.04,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "shruti",
    name: "Shruti",
    nativeName: "శ్రుతి",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native Fluent",
    model: "bulbul:v3",
    description: "Melodious, natural human conversational voice.",
    category: "expressive",
    defaultRate: 1.08,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "suhani",
    name: "Suhani",
    nativeName: "సుహాని",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu & Hindi Bilingual",
    model: "bulbul:v3",
    description: "Friendly customer support voice with clear syllable articulation.",
    category: "conversational",
    defaultRate: 1.05,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "kavitha",
    name: "Kavitha",
    nativeName: "కవిత",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native Traditional",
    model: "bulbul:v3",
    description: "Authoritative yet courteous academic advisor tone.",
    category: "conversational",
    defaultRate: 1.08,
    defaultPitch: 0.99,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "rupali",
    name: "Rupali",
    nativeName: "రూపాలి",
    provider: "sarvam",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu & Multi-regional",
    model: "bulbul:v3",
    description: "Smooth, calm speech rhythm suited for longer consultations.",
    category: "conversational",
    defaultRate: 1.06,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },

  // Telugu Recommended Males
  {
    id: "shubh",
    name: "Shubh",
    nativeName: "శుభ్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native / Clear Hyderabad Cadence",
    model: "bulbul:v3",
    description: "Sarvam recommended primary Telugu male voice. Authoritative, smooth, and natural conversational cadence.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Official Sarvam Telugu Pick",
    defaultRate: 1.1,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "ratan",
    name: "Ratan",
    nativeName: "రతన్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native / Senior Counselor",
    model: "bulbul:v3",
    description: "Sarvam recommended male voice. Mature, trustworthy, and composed admissions counselor tone.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Recommended Male",
    defaultRate: 1.06,
    defaultPitch: 0.96,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
  },
  // Other Bulbul V3 Males
  {
    id: "aditya",
    name: "Aditya",
    nativeName: "ఆదిత్య",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu & English Tech Modern",
    model: "bulbul:v3",
    description: "Modern, energetic tech instructor and counselor voice.",
    category: "conversational",
    defaultRate: 1.12,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "rahul",
    name: "Rahul",
    nativeName: "రాహుల్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Urban",
    model: "bulbul:v3",
    description: "Friendly and approachable student counselor tone.",
    category: "conversational",
    defaultRate: 1.1,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "rohan",
    name: "Rohan",
    nativeName: "రోహన్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Professional",
    model: "bulbul:v3",
    description: "Crisp phone voice with high clarity over mobile connections.",
    category: "telephony",
    defaultRate: 1.14,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "amit",
    name: "Amit",
    nativeName: "అమిత్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu & Multi-lingual",
    model: "bulbul:v3",
    description: "Steady, clear pacing for formal admissions briefings.",
    category: "standard",
    defaultRate: 1.05,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "dev",
    name: "Dev",
    nativeName: "దేవ్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Technical",
    model: "bulbul:v3",
    description: "Direct, confident delivery for curriculum specifications.",
    category: "conversational",
    defaultRate: 1.12,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "varun",
    name: "Varun",
    nativeName: "వరుణ్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native",
    model: "bulbul:v3",
    description: "Warm, conversational cadence for student support.",
    category: "conversational",
    defaultRate: 1.08,
    defaultPitch: 0.99,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "manan",
    name: "Manan",
    nativeName: "మనన్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Fluent",
    model: "bulbul:v3",
    description: "Polite and calm phone advisor tone.",
    category: "conversational",
    defaultRate: 1.06,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "sumit",
    name: "Sumit",
    nativeName: "సుమిత్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu & Hindi Code-Mixed",
    model: "bulbul:v3",
    description: "Dynamic tone with brisk turn-taking cadence.",
    category: "conversational",
    defaultRate: 1.15,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "kabir",
    name: "Kabir",
    nativeName: "కబీర్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Deep & Rich",
    model: "bulbul:v3",
    description: "Deep, resonant male voice with premium timbre.",
    category: "expressive",
    defaultRate: 1.04,
    defaultPitch: 0.94,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "aayan",
    name: "Aayan",
    nativeName: "ఆయాన్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Youthful",
    model: "bulbul:v3",
    description: "Bright and enthusiastic student advisory voice.",
    category: "conversational",
    defaultRate: 1.12,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "ashutosh",
    name: "Ashutosh",
    nativeName: "అశుతోష్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Academic",
    model: "bulbul:v3",
    description: "Structured, patient explanations for course syllabus questions.",
    category: "standard",
    defaultRate: 1.05,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "advait",
    name: "Advait",
    nativeName: "అద్వైత్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Modern",
    model: "bulbul:v3",
    description: "Contemporary admissions tone with low latency phrasing.",
    category: "telephony",
    defaultRate: 1.14,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "anand",
    name: "Anand",
    nativeName: "ఆనంద్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native Telangana",
    model: "bulbul:v3",
    description: "Authentic local Hyderabad tone with natural conversational phrasing.",
    category: "conversational",
    defaultRate: 1.1,
    defaultPitch: 0.97,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "tarun",
    name: "Tarun",
    nativeName: "తరుణ్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Quick Response",
    model: "bulbul:v3",
    description: "Snappy, fast delivery for rapid phone inquiries.",
    category: "telephony",
    defaultRate: 1.2,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "sunny",
    name: "Sunny",
    nativeName: "సన్నీ",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Friendly",
    model: "bulbul:v3",
    description: "Warm, energetic tone with high listener engagement.",
    category: "conversational",
    defaultRate: 1.12,
    defaultPitch: 1.03,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "mani",
    name: "Mani",
    nativeName: "మణి",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Andhra Accent",
    model: "bulbul:v3",
    description: "Classic regional Telugu pronunciation with clear vowels.",
    category: "conversational",
    defaultRate: 1.08,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "gokul",
    name: "Gokul",
    nativeName: "గోకుల్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Soft Spoken",
    model: "bulbul:v3",
    description: "Gentle and patient delivery for complex multi-part questions.",
    category: "conversational",
    defaultRate: 1.06,
    defaultPitch: 0.96,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "vijay",
    name: "Vijay",
    nativeName: "విజయ్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Authoritative",
    model: "bulbul:v3",
    description: "Confident senior coordinator cadence.",
    category: "conversational",
    defaultRate: 1.1,
    defaultPitch: 0.97,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "mohit",
    name: "Mohit",
    nativeName: "మోహిత్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Multilingual",
    model: "bulbul:v3",
    description: "Smooth transition between Telugu and English technical vocabulary.",
    category: "conversational",
    defaultRate: 1.12,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "rehan",
    name: "Rehan",
    nativeName: "రెహాన్",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Urban",
    model: "bulbul:v3",
    description: "Polite customer support voice with clear sentence termination.",
    category: "conversational",
    defaultRate: 1.08,
    defaultPitch: 0.99,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "soham",
    name: "Soham",
    nativeName: "సోహం",
    provider: "sarvam",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Fluent",
    model: "bulbul:v3",
    description: "Measured, clear speech rhythm.",
    category: "standard",
    defaultRate: 1.06,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
  },
];

// 2. ELEVENLABS - Dynamic & Telugu/Indic Conversational Library
export const ELEVENLABS_SPEAKERS: VoiceSpeaker[] = [
  {
    id: "eleven-sravani-telugu",
    name: "Sravani (Telugu Native)",
    nativeName: "శ్రావణి",
    provider: "elevenlabs",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native / Hyderabad Conversational",
    model: "eleven_turbo_v2_5",
    description: "Fine-tuned Telugu female voice designed specifically for real-time conversational turn taking.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Top Telugu Conversational Pick",
    defaultRate: 1.15,
    defaultPitch: 1.04,
    supportedSampleRates: [16000, 22050, 24000, 44100],
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "eleven-pranathi-telugu",
    name: "Pranathi (Telugu Fluent)",
    nativeName: "ప్రణతి",
    provider: "elevenlabs",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Urban & Tanglish Code-Mixed",
    model: "eleven_multilingual_v2",
    description: "High-expression model with superb code-mixing between Telugu and English technical terms.",
    category: "expressive",
    recommendedForTelugu: true,
    recommendedTag: "🌸 Warm & Code-Mixed",
    defaultRate: 1.1,
    defaultPitch: 1.02,
    supportedSampleRates: [16000, 24000, 44100],
    avatarUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "eleven-divya-telugu",
    name: "Divya (Executive Counselor)",
    nativeName: "దివ్య",
    provider: "elevenlabs",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu & Indian English Bilingual",
    model: "eleven_turbo_v2_5",
    description: "Crisp, professional, and rapid-response phone counselor persona.",
    category: "telephony",
    recommendedForTelugu: true,
    recommendedTag: "⚡ Fast Phone Mode",
    defaultRate: 1.2,
    defaultPitch: 1.05,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "eleven-aditya-telugu",
    name: "Aditya (Senior Advisor)",
    nativeName: "ఆదిత్య",
    provider: "elevenlabs",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native / Tech Admissions",
    model: "eleven_turbo_v2_5",
    description: "Clear, confident male conversational voice with seamless Telugu pronunciation.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Top Telugu Male Pick",
    defaultRate: 1.12,
    defaultPitch: 0.98,
    supportedSampleRates: [16000, 24000, 44100],
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "eleven-karthik-telugu",
    name: "Karthik (Support Lead)",
    nativeName: "కార్తీక్",
    provider: "elevenlabs",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Hyderabad Accent",
    model: "eleven_flash_v2_5",
    description: "Ultra-low latency streaming model optimized for interactive phone dialogues.",
    category: "telephony",
    defaultRate: 1.15,
    defaultPitch: 0.99,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
  },
];

// 3. GOOGLE CLOUD CHIRP 3 HD - Full Telugu Catalog
export const GOOGLE_CHIRP_SPEAKERS: VoiceSpeaker[] = [
  // Females
  {
    id: "te-IN-Chirp3-HD-Aoede",
    name: "Aoede (Chirp 3 HD)",
    nativeName: "అయోడి",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Native Neural Telugu",
    model: "chirp-3-hd",
    description: "Google Cloud Chirp 3 HD high-fidelity neural female voice with natural Telugu intonation.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Recommended Chirp Female",
    defaultRate: 1.12,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000, 48000],
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "te-IN-Chirp3-HD-Autonoe",
    name: "Autonoe (Chirp 3 HD)",
    nativeName: "ఆటోనో",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Melodic Cadence",
    model: "chirp-3-hd",
    description: "Smooth, articulate female voice with clear Telugu vowels and conversational cadence.",
    category: "conversational",
    defaultRate: 1.1,
    defaultPitch: 1.04,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Callirrhoe",
    name: "Callirrhoe (Chirp 3 HD)",
    nativeName: "కాలిరోయి",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Conversational",
    model: "chirp-3-hd",
    description: "Warm admissions counselor tone with natural sentence pauses.",
    category: "conversational",
    defaultRate: 1.08,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Despina",
    name: "Despina (Chirp 3 HD)",
    nativeName: "డెస్పినా",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Expressive",
    model: "chirp-3-hd",
    description: "Energetic and crisp, suited for telephone reception and quick turns.",
    category: "telephony",
    defaultRate: 1.18,
    defaultPitch: 1.05,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Erinome",
    name: "Erinome (Chirp 3 HD)",
    nativeName: "ఎరినోమ్",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Gentle",
    model: "chirp-3-hd",
    description: "Patient, supportive tone for multi-topic consultations.",
    category: "conversational",
    defaultRate: 1.06,
    defaultPitch: 0.99,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Gacrux",
    name: "Gacrux (Chirp 3 HD)",
    nativeName: "గాక్రక్స్",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Articulate",
    model: "chirp-3-hd",
    description: "Crisp consonants and excellent clarity in noisy environments.",
    category: "conversational",
    defaultRate: 1.12,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Kore",
    name: "Kore (Chirp 3 HD)",
    nativeName: "కోరే",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Friendly",
    model: "chirp-3-hd",
    description: "Youthful and engaging female voice.",
    category: "conversational",
    defaultRate: 1.1,
    defaultPitch: 1.06,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Laomedeia",
    name: "Laomedeia (Chirp 3 HD)",
    nativeName: "లావోమెడియా",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Calm",
    model: "chirp-3-hd",
    description: "Steady and composed phone advisor.",
    category: "standard",
    defaultRate: 1.05,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Leda",
    name: "Leda (Chirp 3 HD)",
    nativeName: "లెడా",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Conversational",
    model: "chirp-3-hd",
    description: "Natural rhythm with organic inflection on question endings.",
    category: "conversational",
    defaultRate: 1.12,
    defaultPitch: 1.03,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Pulcherrima",
    name: "Pulcherrima (Chirp 3 HD)",
    nativeName: "పుల్చెరిమా",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Professional",
    model: "chirp-3-hd",
    description: "Polished corporate reception tone.",
    category: "conversational",
    defaultRate: 1.08,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Sulafat",
    name: "Sulafat (Chirp 3 HD)",
    nativeName: "సులాఫాట్",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Warm",
    model: "chirp-3-hd",
    description: "Gentle and welcoming tone.",
    category: "conversational",
    defaultRate: 1.08,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Vindemiatrix",
    name: "Vindemiatrix (Chirp 3 HD)",
    nativeName: "విండెమియాట్రిక్స్",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Fast Telephony",
    model: "chirp-3-hd",
    description: "Low-latency optimized phone voice.",
    category: "telephony",
    defaultRate: 1.2,
    defaultPitch: 1.04,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Zephyr",
    name: "Zephyr (Chirp 3 HD)",
    nativeName: "జెఫైర్",
    provider: "google_chirp",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Expressive",
    model: "chirp-3-hd",
    description: "Expressive and modern delivery.",
    category: "expressive",
    defaultRate: 1.1,
    defaultPitch: 1.03,
    supportedSampleRates: [8000, 16000, 24000],
  },

  // Males
  {
    id: "te-IN-Chirp3-HD-Algieba",
    name: "Algieba (Chirp 3 HD)",
    nativeName: "అల్గియేబా",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Native Neural Male",
    model: "chirp-3-hd",
    description: "Google Cloud Chirp 3 HD primary male voice with rich tone and clear Telugu articulation.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Recommended Chirp Male",
    defaultRate: 1.1,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000, 48000],
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "te-IN-Chirp3-HD-Alnilam",
    name: "Alnilam (Chirp 3 HD)",
    nativeName: "అల్నిలం",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Authoritative",
    model: "chirp-3-hd",
    description: "Strong, composed admissions counselor delivery.",
    category: "conversational",
    defaultRate: 1.06,
    defaultPitch: 0.96,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Charon",
    name: "Charon (Chirp 3 HD)",
    nativeName: "కారాన్",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Deep",
    model: "chirp-3-hd",
    description: "Deep, resonant male voice with excellent acoustic presence.",
    category: "expressive",
    defaultRate: 1.05,
    defaultPitch: 0.92,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Enceladus",
    name: "Enceladus (Chirp 3 HD)",
    nativeName: "ఎన్సెలాడస్",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Conversational",
    model: "chirp-3-hd",
    description: "Natural pacing and polite inquiry handling.",
    category: "conversational",
    defaultRate: 1.12,
    defaultPitch: 0.99,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Fenrir",
    name: "Fenrir (Chirp 3 HD)",
    nativeName: "ఫెన్రిర్",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Fast Telephony",
    model: "chirp-3-hd",
    description: "Snappy, fast delivery for low latency phone turn taking.",
    category: "telephony",
    defaultRate: 1.18,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Iapetus",
    name: "Iapetus (Chirp 3 HD)",
    nativeName: "ఇయాపెటస్",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Steady",
    model: "chirp-3-hd",
    description: "Measured, clear instructional tone.",
    category: "standard",
    defaultRate: 1.05,
    defaultPitch: 0.97,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Orus",
    name: "Orus (Chirp 3 HD)",
    nativeName: "ఒరస్",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Warm",
    model: "chirp-3-hd",
    description: "Friendly, polite student advisor cadence.",
    category: "conversational",
    defaultRate: 1.1,
    defaultPitch: 0.99,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Puck",
    name: "Puck (Chirp 3 HD)",
    nativeName: "పక్",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Youthful",
    model: "chirp-3-hd",
    description: "Energetic and lively male tone.",
    category: "conversational",
    defaultRate: 1.14,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Rasalgethi",
    name: "Rasalgethi (Chirp 3 HD)",
    nativeName: "రసాల్గెతి",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Mature",
    model: "chirp-3-hd",
    description: "Senior advisory voice with refined diction.",
    category: "conversational",
    defaultRate: 1.06,
    defaultPitch: 0.95,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Sadachbia",
    name: "Sadachbia (Chirp 3 HD)",
    nativeName: "సదాచ్బియా",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Technical",
    model: "chirp-3-hd",
    description: "Accurate pronunciation of software course names.",
    category: "conversational",
    defaultRate: 1.1,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Sadaltager",
    name: "Sadaltager (Chirp 3 HD)",
    nativeName: "సదల్తాజర్",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Smooth",
    model: "chirp-3-hd",
    description: "Polite customer reception cadence.",
    category: "conversational",
    defaultRate: 1.08,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Schedar",
    name: "Schedar (Chirp 3 HD)",
    nativeName: "షెడార్",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Expressive",
    model: "chirp-3-hd",
    description: "Dynamic pitch variation with human cadence.",
    category: "expressive",
    defaultRate: 1.12,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Umbriel",
    name: "Umbriel (Chirp 3 HD)",
    nativeName: "ఉంబ్రియల్",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Deep Rich",
    model: "chirp-3-hd",
    description: "Deep, trustworthy admissions tone.",
    category: "standard",
    defaultRate: 1.05,
    defaultPitch: 0.94,
    supportedSampleRates: [8000, 16000, 24000],
  },
  {
    id: "te-IN-Chirp3-HD-Zubenelgenubi",
    name: "Zubenelgenubi (Chirp 3 HD)",
    nativeName: "జుబెనెల్జెనుబి",
    provider: "google_chirp",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Chirp 3 HD Quick Phone",
    model: "chirp-3-hd",
    description: "Snappy responses with minimal latency.",
    category: "telephony",
    defaultRate: 1.16,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
];

// 4. MURF AI - Telugu & Indic Conversational Catalog
export const MURF_SPEAKERS: VoiceSpeaker[] = [
  {
    id: "murf-te-swathi",
    name: "Swathi (Murf Conversational)",
    nativeName: "స్వాతి",
    provider: "murf",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native / South Indian Natural",
    model: "murf-v2-conversational",
    description: "Murf AI natural Telugu female voice with warm phone customer support intonation.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Recommended Murf Female",
    defaultRate: 1.1,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000, 44100],
    avatarUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "murf-te-anusha",
    name: "Anusha (Murf Phone Reception)",
    nativeName: "అనూష",
    provider: "murf",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Urban Hyderabad",
    model: "murf-v2-conversational",
    description: "Fast, energetic admissions coordinator persona with high conversational agility.",
    category: "telephony",
    recommendedForTelugu: true,
    recommendedTag: "⚡ Fast Murf Receptionist",
    defaultRate: 1.18,
    defaultPitch: 1.04,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "murf-te-bhavani",
    name: "Bhavani (Murf Empathetic)",
    nativeName: "భవాని",
    provider: "murf",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Gentle & Reassuring",
    model: "murf-v2-expressive",
    description: "Soothing tone for calming hesitant callers and providing detailed assistance.",
    category: "expressive",
    defaultRate: 1.06,
    defaultPitch: 0.99,
    supportedSampleRates: [16000, 24000],
  },
  {
    id: "murf-te-ravi",
    name: "Ravi (Murf Academic Advisor)",
    nativeName: "రవి",
    provider: "murf",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Native / Formal Academic",
    model: "murf-v2-conversational",
    description: "Murf AI clear male admissions voice with articulate technical course phrasing.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Recommended Murf Male",
    defaultRate: 1.1,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "murf-te-karthik",
    name: "Karthik (Murf Dynamic)",
    nativeName: "కార్తీక్",
    provider: "murf",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Telugu Modern Tech",
    model: "murf-v2-conversational",
    description: "Dynamic male counselor tone with high clarity across mobile codecs.",
    category: "conversational",
    defaultRate: 1.12,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
  },
];

// 5. OPEN-SOURCE NEURAL SPEECH ENGINE (Edge Neural - 100% Free & Unlimited)
export const EDGE_NEURAL_SPEAKERS: VoiceSpeaker[] = [
  // Conversational Females
  {
    id: "edge-te-shruti",
    name: "Shruti (Open-Source Flagship Telugu)",
    nativeName: "శ్రుతి",
    provider: "edge_neural",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Open Neural Conversational Telugu (Studio Natural)",
    model: "te-IN-ShrutiNeural",
    description: "Open-source high-fidelity Telugu neural voice. 100% free and unlimited with authentic human breathing, native Telugu diction, and fluent articulation of complex course inquiries.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "🔥 Open Source Flagship (Zero Cost, No Quota)",
    defaultRate: 1.03,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "edge-te-sravani",
    name: "Sravani (Melodic Senior Receptionist)",
    nativeName: "శ్రావణి",
    provider: "edge_neural",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Melodic Polite Receptionist Cadence",
    model: "te-IN-ShrutiNeural [Acoustic-Tuned]",
    description: "Polite, welcoming Telugu admissions front-desk tone. Soft articulation, warm melodic pitch, and gentle pacing ideal for first-time callers.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Front-Desk Favorite",
    defaultRate: 1.02,
    defaultPitch: 1.05,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "edge-te-kavya",
    name: "Kavya (Empathetic Admissions Counselor)",
    nativeName: "కావ్య",
    provider: "edge_neural",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Empathetic Soft-Spoken Counseling",
    model: "te-IN-ShrutiNeural [Acoustic-Tuned]",
    description: "Patient and empathetic counselor voice. Unhurried cadence with soothing natural breath intervals, tailored for fee explanations and placement guidance.",
    category: "expressive",
    recommendedForTelugu: true,
    recommendedTag: "✨ Empathetic Tone",
    defaultRate: 0.98,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "edge-te-divya",
    name: "Divya (Fast-Track Academic Coordinator)",
    nativeName: "దివ్య",
    provider: "edge_neural",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Dynamic Energetic Hyderabad Cadence",
    model: "te-IN-ShrutiNeural [Acoustic-Tuned]",
    description: "Crisp, dynamic Hyderabad Telugu with quick, confident replies. Ideal for high-volume inquiries and fast-track curriculum breakdowns.",
    category: "telephony",
    recommendedForTelugu: true,
    recommendedTag: "⚡ Fast & Energetic",
    defaultRate: 1.06,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "edge-te-pranathi",
    name: "Pranathi (Lead Student Counselor)",
    nativeName: "ప్రణతి",
    provider: "edge_neural",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Warm Fluent Conversational Flow",
    model: "te-IN-ShrutiNeural [Acoustic-Tuned]",
    description: "Natural, engaging student counselor voice. Highly articulate with balanced pitch and friendly conversational intonation.",
    category: "conversational",
    recommendedForTelugu: true,
    defaultRate: 1.01,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "edge-te-ramya",
    name: "Ramya (Career Placement Mentor)",
    nativeName: "రమ్య",
    provider: "edge_neural",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Calm Supportive Mentorship",
    model: "te-IN-ShrutiNeural [Acoustic-Tuned]",
    description: "Supportive, grounded mentor tone. Focuses on career reassurance, mock interviews, and placement track counseling.",
    category: "conversational",
    recommendedForTelugu: true,
    defaultRate: 0.99,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1548142813-c348350df52b?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "edge-te-swathi",
    name: "Swathi (Student Success & Labs Advisor)",
    nativeName: "స్వాతి",
    provider: "edge_neural",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Supportive Hands-on Lab Guidance",
    model: "te-IN-ShrutiNeural [Acoustic-Tuned]",
    description: "Friendly and upbeat mentor voice specialized in hands-on lab schedules, doubts clearance, and project support.",
    category: "conversational",
    recommendedForTelugu: true,
    defaultRate: 1.03,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80",
  },

  // Authoritative & Dynamic Males
  {
    id: "edge-te-mohan",
    name: "Mohan (Deep Resonance Senior Academic Director)",
    nativeName: "మోహన్",
    provider: "edge_neural",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Authoritative Baritone Academic Delivery",
    model: "te-IN-MohanNeural",
    description: "Deep baritone Telugu male voice conveying authority, trust, and academic excellence. Open-source zero-cost neural model with natural pacing and studio clarity.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "🎙️ Authoritative Baritone Male",
    defaultRate: 0.98,
    defaultPitch: 0.95,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "edge-te-rajesh",
    name: "Rajesh (Tech Placement Lead & Coding Mentor)",
    nativeName: "రాజేష్",
    provider: "edge_neural",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Dynamic Energetic Technical Lead",
    model: "te-IN-MohanNeural [Acoustic-Tuned]",
    description: "Energetic and relatable technical lead male voice. Quick cadence with natural delivery of technical terms like Python, Java, AWS, and Git.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "⚡ Technical Lead Male",
    defaultRate: 1.06,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "edge-te-venkat",
    name: "Venkat (Senior Corporate Trainer)",
    nativeName: "వెంకట్",
    provider: "edge_neural",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Corporate Senior Lecturer Cadence",
    model: "te-IN-MohanNeural [Acoustic-Tuned]",
    description: "Articulate, measured corporate trainer voice with clear pacing and professional modulation.",
    category: "standard",
    recommendedForTelugu: true,
    defaultRate: 1.01,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "edge-te-kalyan",
    name: "Kalyan (Admissions & Career Counselor)",
    nativeName: "కల్యాణ్",
    provider: "edge_neural",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Friendly Supportive Counselor Delivery",
    model: "te-IN-MohanNeural [Acoustic-Tuned]",
    description: "Warm and encouraging counselor male voice who helps students choose the best technology track.",
    category: "conversational",
    recommendedForTelugu: true,
    defaultRate: 1.02,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
  },

  // Indian English Bilingual Voices
  {
    id: "edge-en-neerja",
    name: "Neerja (Open-Source Expressive Indian English)",
    nativeName: "నీర్జా",
    provider: "edge_neural",
    gender: "female",
    language: "en-IN",
    languageName: "English (India)",
    accent: "Open Neural Expressive Indian English",
    model: "en-IN-NeerjaExpressiveNeural",
    description: "Ultra-expressive Indian English corporate admissions advisor. Perfect for bilingual course counseling and fee breakdowns.",
    category: "expressive",
    recommendedForTelugu: true,
    recommendedTag: "⭐ Bilingual Indian English Pick",
    defaultRate: 1.03,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "edge-en-prabhat",
    name: "Prabhat (Open-Source Neural Indian English)",
    nativeName: "ప్రభాత్",
    provider: "edge_neural",
    gender: "male",
    language: "en-IN",
    languageName: "English (India)",
    accent: "Open Neural Authoritative Indian English",
    model: "en-IN-PrabhatNeural",
    description: "Articulate, authoritative Indian English male voice for technical training counseling and corporate certifications.",
    category: "conversational",
    recommendedForTelugu: false,
    defaultRate: 1.02,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
  },
];

// 6. AI4BHARAT INDIC & BHASHINI OPEN RESEARCH SUITE (IIT Madras Open Source Models)
export const AI4BHARAT_INDIC_SPEAKERS: VoiceSpeaker[] = [
  {
    id: "ai4bharat-te-ananya",
    name: "Ananya (AI4Bharat Indic-Parler Female)",
    nativeName: "అనన్య",
    provider: "ai4bharat_indic",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Native Dialect Authentic Conversational",
    model: "ai4bharat/indic-parler-tts-telugu",
    description: "Developed from IIT Madras AI4Bharat speech research. Authentic native Telugu dialect with pure linguistic inflection and zero robotic pitch artifacts.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "🏛️ IIT Madras Indic Research Pick",
    defaultRate: 1.0,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "ai4bharat-te-praveen",
    name: "Praveen (AI4Bharat Indic-Parler Male)",
    nativeName: "ప్రవీణ్",
    provider: "ai4bharat_indic",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Academic Lecturer Indic Cadence",
    model: "ai4bharat/indic-parler-tts-telugu-male",
    description: "Grounded, scholarly Telugu male speaker trained on extensive academic and spoken discourse. Delivers clean, unhurried course curriculum overviews.",
    category: "conversational",
    recommendedForTelugu: true,
    recommendedTag: "🏛️ IIT Madras Academic Male",
    defaultRate: 1.0,
    defaultPitch: 0.98,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "ai4bharat-te-chitra",
    name: "Chitra (AI4Bharat IndicTTS FastPitch)",
    nativeName: "చిత్ర",
    provider: "ai4bharat_indic",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "High Clarity Acoustic Research Female",
    model: "indic-tts-fastpitch-te",
    description: "Acoustically normalized IndicTTS model architecture providing razor-sharp syllable separation and natural consonant voicing for technical queries.",
    category: "standard",
    recommendedForTelugu: true,
    defaultRate: 1.03,
    defaultPitch: 1.04,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "ai4bharat-te-sai",
    name: "Sai (AI4Bharat IndicTTS FastPitch Male)",
    nativeName: "సాయి",
    provider: "ai4bharat_indic",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Clear Paced Acoustic Delivery",
    model: "indic-tts-fastpitch-te-male",
    description: "Clear and articulate male model optimized for instruction delivery, syllabic accuracy, and multi-sentence course explanations.",
    category: "standard",
    recommendedForTelugu: true,
    defaultRate: 1.02,
    defaultPitch: 1.0,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "ai4bharat-te-bindu",
    name: "Bindu (Bhashini Open Indic Receptionist)",
    nativeName: "బిందు",
    provider: "ai4bharat_indic",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Official Public Support Cadence",
    model: "bhashini-indic-vits-telugu",
    description: "Public service and helpline speech model from the National Language Translation Mission. Polite, crystal-clear telephone cadence.",
    category: "telephony",
    recommendedForTelugu: true,
    defaultRate: 1.02,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "meta-mms-te-female",
    name: "Aruna (Meta MMS Open-Source VITS Female)",
    nativeName: "అరుణ",
    provider: "ai4bharat_indic",
    gender: "female",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Open VITS Acoustic Wave Modeling",
    model: "meta/mms-tts-tel (VITS Architecture)",
    description: "Meta AI's open-source Massively Multilingual Speech model for Telugu. Variational Inference with Adversarial Learning for end-to-end natural waveforms.",
    category: "expressive",
    recommendedForTelugu: true,
    defaultRate: 1.01,
    defaultPitch: 1.02,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "meta-mms-te-male",
    name: "Manoj (Meta MMS Open-Source VITS Male)",
    nativeName: "మనోజ్",
    provider: "ai4bharat_indic",
    gender: "male",
    language: "te-IN",
    languageName: "Telugu (India)",
    accent: "Open VITS Deep Wave Modeling Male",
    model: "meta/mms-tts-tel-male (VITS Architecture)",
    description: "Meta MMS open architecture male Telugu voice. Smooth continuous fundamental frequency contours with solid telephony intelligibility.",
    category: "conversational",
    recommendedForTelugu: true,
    defaultRate: 0.99,
    defaultPitch: 0.96,
    supportedSampleRates: [8000, 16000, 24000],
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
  },
];

export const VOICE_PROVIDERS: VoiceProviderConfig[] = [
  {
    id: "google_gemini",
    name: "Google Gemini Voice",
    badge: "Gemini Flash TTS (Zero Cost)",
    brandColor: "#4285f4",
    tagline: "Ultra-natural generative voices powered directly by Google Gemini.",
    description: "Official Google Gemini speech synthesis with Kore, Puck, Aoede, Charon, and Leda. Delivers human-level prosody, dynamic conversational inflection, and perfect Telugu-English code-mixing with zero extra API costs.",
    models: [
      { id: "gemini-3.1-flash-tts-preview", name: "Gemini 3.1 Flash TTS", description: "Flagship Google Gemini multimodal speech generator with ultra-natural conversational tone", latencyClass: "ultra-low" },
    ],
    supportedSampleRates: [8000, 16000, 24000, 48000],
    supportsStreaming: true,
    supportsBargeIn: true,
    supportsPhoneMode8kHz: true,
    docsUrl: "https://ai.google.dev",
    speakers: GOOGLE_GEMINI_SPEAKERS,
  },
  {
    id: "sarvam",
    name: "Sarvam AI",
    badge: "Bulbul V3 Indic Engine",
    brandColor: "#6366f1",
    tagline: "India's frontier AI speech engine with native Telugu phonetics.",
    description: "Sarvam Bulbul V3 offers the most extensive native Indic speaker catalog with fine-grained pitch, pace, and telephony 8kHz/16kHz/24kHz streaming capabilities.",
    models: [
      { id: "bulbul:v3", name: "Bulbul V3 (Latest)", description: "State-of-the-art multilingual Indic TTS with rich Telugu regional inflections", latencyClass: "ultra-low" },
      { id: "bulbul:v2", name: "Bulbul V2 (Legacy)", description: "Standard Indic neural model", latencyClass: "low" },
    ],
    supportedSampleRates: [8000, 16000, 24000],
    supportsStreaming: true,
    supportsBargeIn: true,
    supportsPhoneMode8kHz: true,
    docsUrl: "https://docs.sarvam.ai",
    speakers: SARVAM_SPEAKERS,
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    badge: "Multilingual & Turbo V2.5",
    brandColor: "#0ea5e9",
    tagline: "Ultra-expressive generative voice with sub-250ms streaming.",
    description: "ElevenLabs Multilingual V2 and Turbo V2.5 deliver human conversational nuance, code-mixed Tanglish handling, and emotional tone responsiveness.",
    models: [
      { id: "eleven_turbo_v2_5", name: "Eleven Turbo V2.5", description: "Ultra-low latency streaming model optimized for interactive phone dialogues", latencyClass: "ultra-low" },
      { id: "eleven_multilingual_v2", name: "Eleven Multilingual V2", description: "Highest audio fidelity and emotional stability across Telugu-English mixing", latencyClass: "low" },
      { id: "eleven_flash_v2_5", name: "Eleven Flash V2.5", description: "Extreme low latency for rapid telephony turn-taking", latencyClass: "ultra-low" },
    ],
    supportedSampleRates: [8000, 16000, 22050, 24000, 44100],
    supportsStreaming: true,
    supportsBargeIn: true,
    supportsPhoneMode8kHz: true,
    docsUrl: "https://elevenlabs.io/docs",
    speakers: ELEVENLABS_SPEAKERS,
  },
  {
    id: "google_chirp",
    name: "Google Cloud Chirp 3 HD",
    badge: "te-IN Chirp 3 HD",
    brandColor: "#10b981",
    tagline: "Google's next-generation 14+ male & 13+ female Telugu Chirp models.",
    description: "Enterprise-grade Chirp 3 HD architecture providing extensive celestial voice variants (Aoede, Algieba, Charon, etc.) with robust SSML and telephony pitch control.",
    models: [
      { id: "chirp-3-hd", name: "Chirp 3 HD (te-IN)", description: "Google's flagship generative speech foundation model for Indic languages", latencyClass: "low" },
      { id: "neural2", name: "Google Neural2 (te-IN)", description: "Low-latency neural telephony synthesizer", latencyClass: "low" },
    ],
    supportedSampleRates: [8000, 16000, 24000, 48000],
    supportsStreaming: true,
    supportsBargeIn: true,
    supportsPhoneMode8kHz: true,
    docsUrl: "https://cloud.google.com/text-to-speech/docs",
    speakers: GOOGLE_CHIRP_SPEAKERS,
  },
  {
    id: "murf",
    name: "Murf AI",
    badge: "Murf V2 Conversational",
    brandColor: "#f59e0b",
    tagline: "Studio-grade Telugu conversational voices with pause & style controls.",
    description: "Murf Voice Engine offers high-clarity Telugu voices with granular speed, pitch, natural pause insertion, and conversational emphasis controls.",
    models: [
      { id: "murf-v2-conversational", name: "Murf V2 Conversational", description: "Natural phone dialogue and customer support cadence", latencyClass: "low" },
      { id: "murf-v2-expressive", name: "Murf V2 Expressive", description: "Rich intonation and empathetic modulation", latencyClass: "standard" },
    ],
    supportedSampleRates: [8000, 16000, 24000, 44100],
    supportsStreaming: true,
    supportsBargeIn: true,
    supportsPhoneMode8kHz: true,
    docsUrl: "https://murf.ai/api",
    speakers: MURF_SPEAKERS,
  },
  {
    id: "edge_neural",
    name: "Open-Source Neural Engine",
    badge: "Open Neural (100% Free & Unlimited)",
    brandColor: "#059669",
    tagline: "Ultra-natural open-source neural speech models with zero quota limits.",
    description: "Fully open-source neural text-to-speech engine powered by Edge Neural Voice technology. Generates authentic Telugu (Shruti & Mohan) and Indian English (Neerja & Prabhat) with true human breath intervals, native conversational inflection, and zero API costs or daily limits.",
    models: [
      { id: "edge-neural-v1", name: "Open-Source Neural Indic V1", description: "Studio-grade neural speech model with natural phonetics and continuous prosody", latencyClass: "ultra-low" },
    ],
    supportedSampleRates: [8000, 16000, 24000],
    supportsStreaming: true,
    supportsBargeIn: true,
    supportsPhoneMode8kHz: true,
    docsUrl: "https://github.com/microsoft/edge-tts",
    speakers: EDGE_NEURAL_SPEAKERS,
  },
  {
    id: "ai4bharat_indic",
    name: "AI4Bharat & Bhashini Open Models",
    badge: "IIT Madras Research (Apache 2.0 Open Source)",
    brandColor: "#ea580c",
    tagline: "Frontier open-source Indic speech models from IIT Madras & Bhashini.",
    description: "Authentic native Telugu dialect research models including Indic-Parler TTS, IndicTTS FastPitch, and Meta MMS open speech architectures. Pre-trained on thousands of hours of native Indic spoken recordings for true conversational authenticity without commercial quotas.",
    models: [
      { id: "indic-parler-tts-telugu", name: "Indic-Parler TTS (v1.0)", description: "IIT Madras flagship open conversational Indic model", latencyClass: "ultra-low" },
      { id: "indic-tts-fastpitch-te", name: "IndicTTS FastPitch (v2.2)", description: "High acoustic clarity model with phonetic syllable isolation", latencyClass: "low" },
      { id: "bhashini-indic-vits-telugu", name: "Bhashini VITS Public", description: "National Language Translation Mission public telephony voice", latencyClass: "low" },
      { id: "meta-mms-telugu", name: "Meta MMS Open Architecture", description: "End-to-end waveform acoustic synthesis", latencyClass: "low" },
    ],
    supportedSampleRates: [8000, 16000, 24000],
    supportsStreaming: true,
    supportsBargeIn: true,
    supportsPhoneMode8kHz: true,
    docsUrl: "https://ai4bharat.iitm.ac.in",
    speakers: AI4BHARAT_INDIC_SPEAKERS,
  },
];

export function getAllSpeakers(): VoiceSpeaker[] {
  return [
    ...EDGE_NEURAL_SPEAKERS,
    ...AI4BHARAT_INDIC_SPEAKERS,
    ...GOOGLE_GEMINI_SPEAKERS,
    ...SARVAM_SPEAKERS,
    ...ELEVENLABS_SPEAKERS,
    ...GOOGLE_CHIRP_SPEAKERS,
    ...MURF_SPEAKERS,
  ];
}

export function findSpeakerById(speakerId: string): VoiceSpeaker | undefined {
  return getAllSpeakers().find((s) => s.id === speakerId);
}
